FROM rust:1.72 as builder

WORKDIR /app
COPY . .
RUN cargo build --release

# Use Ubuntu 22.04 as base image which has newer GLIBC
FROM ubuntu:22.04
WORKDIR /app

# Install required dependencies
RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# Copy the binary from builder
COPY --from=builder /app/target/release/docker-run /app/docker-run

# Environment variables
ENV SERVER_LISTEN_ADDR=0.0.0.0
ENV SERVER_LISTEN_PORT=10000
ENV SERVER_WORKER_THREADS=10
ENV API_ACCESS_TOKEN=some-secret-token
ENV DOCKER_UNIX_SOCKET_PATH=/var/run/docker.sock
ENV DOCKER_UNIX_SOCKET_READ_TIMEOUT=3
ENV DOCKER_UNIX_SOCKET_WRITE_TIMEOUT=3
ENV DOCKER_CONTAINER_HOSTNAME=glot
ENV DOCKER_CONTAINER_USER=glot
ENV DOCKER_CONTAINER_MEMORY=1000000000
ENV DOCKER_CONTAINER_NETWORK_DISABLED=true
ENV DOCKER_CONTAINER_ULIMIT_NOFILE_SOFT=90
ENV DOCKER_CONTAINER_ULIMIT_NOFILE_HARD=100
ENV DOCKER_CONTAINER_ULIMIT_NPROC_SOFT=90
ENV DOCKER_CONTAINER_ULIMIT_NPROC_HARD=100
ENV DOCKER_CONTAINER_CAP_DROP="MKNOD NET_RAW NET_BIND_SERVICE"
ENV DOCKER_CONTAINER_READONLY_ROOTFS=true
ENV RUST_LOG=debug
ENV RUN_MAX_EXECUTION_TIME=15

EXPOSE 10000
CMD ["./docker-run"]